### ISSUE TITLE
Shapefiles SRSs, +over or not?

### ISSUE THREAD

**Issue by StyXman** [imagico/poly_grid#1]
I'm having issues rendering osm-carto, oceans and seas do not render. I remembered [this comment](https://github.com/gravitystorm/openstreetmap-carto/issues/2101#issuecomment-234705904) and took a look:

    $ ogrinfo -al data/water-polygons-split-3857/water_polygons.shp
    INFO: Open of `data/water-polygons-split-3857/water_polygons.shp'
        using driver `ESRI Shapefile' successful.

    Layer name: water_polygons
    Metadata:
    DBF_DATE_LAST_UPDATE=2019-05-28
    Geometry: Polygon
    Feature Count: 14488
    Extent: (-20037508.340000, -14773407.419294) - (20037508.340000, 20037508.340000)
    Layer SRS WKT:
    PROJCS["WGS 84 / Pseudo-Mercator",
        GEOGCS["WGS 84",
            DATUM["WGS_1984",
                SPHEROID["WGS 84",6378137,298.257223563,
                    AUTHORITY["EPSG","7030"]],
                AUTHORITY["EPSG","6326"]],
            PRIMEM["Greenwich",0,
                AUTHORITY["EPSG","8901"]],
            UNIT["degree",0.0174532925199433,
                AUTHORITY["EPSG","9122"]],
            AUTHORITY["EPSG","4326"]],
        PROJECTION["Mercator_1SP"],
        PARAMETER["central_meridian",0],
        PARAMETER["scale_factor",1],
        PARAMETER["false_easting",0],
        PARAMETER["false_northing",0],
        UNIT["metre",1,
            AUTHORITY["EPSG","9001"]],
        AXIS["X",EAST],
        AXIS["Y",NORTH],
        EXTENSION["PROJ4","+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs"],
        AUTHORITY["EPSG","3857"]]
    FID: Integer64 (11.0)

The SRS seem to still lack the `+over` parameter. Now, I read again all that thread and @imagico mentions that `mapnik` back then was reprojecting to some other projection and then back, ruining everything. 

In my case, the issue is that no seas or oceans are rendered, using either the water polygons or the simplified version. Turning on Mapnik's debug messages I see that the issue is that for some reason, mapnik is not finding things to render for those layers:

    agg_renderer: Start processing layer=ocean-lz
    agg_renderer: -- datasource=0x1f03ee0
    agg_renderer: -- query_extent=box2d(460456.6583899010438472,5080310.6479459535330534,1086628.7941020664293319,5706482.7836581189185381)
    agg_renderer: Start processing style
    shape_index_featureset: 0 features
    agg_renderer: End processing style
    agg_renderer: End layer processing

I'm writing an email to the mapnik google group to try to figure all this out (I'm definitely not an expert on projections, and I can't even understand in what projection those coordinates are), but maybe you can shed a light too. Remember, `osm-carto`'s SRS is `srs="+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over"`.

**Comment by imagico** [comment]
First:  Wrong issue tracker - the process for the water polygons is maintained on

https://github.com/fossgis/osmdata

and is not using poly_grid any more.

Regarding your problem - as reported by ogrinfo with the new process the water polygons (and fwiw also the land polygons) do not extend across the 180-degree meridian - neither the simplified nor the non-simplified version.  You can therefore reproject the Mercator variants without problems if you want/need to.

Generally speaking - if you don't get anything rendered from the shapefile layers it is unlikely that this is a problem of the shapefile content and you should probably check with a test file containing just a few very simple geometries if the problem  is indeed specific to the data in the water polygon files.

**Comment by imagico** [comment]
Note https://github.com/gravitystorm/openstreetmap-carto/issues/2101#issuecomment-485286131 indicates a problem with mapnik's shapeindex.

**Comment by StyXman** [comment]
Yes, I kinda did that, as `./scripts/get_shapefiles.py` handles the downloading and indexing of the files.

**Comment by StyXman** [comment]
In case you're interested in the discussion over mapnik, here's the link: https://groups.google.com/forum/#!topic/mapnik/mXmbxDlfQZA

Should I close this?

**Comment by StyXman** [comment]
For the record, the issue seems to lie on mapnik-master, which I have been using locally.
